### PR TITLE
Update MySQL version from 2006 to 2016

### PR DESCRIPTION
**Pull request by cyrichardson**
As requested b y Mark Woodbury

### CODE REVIEW

**Comment by cyrichardson** [comment]
@edwardjrp New PR... just giving you a heads up. We'll see how this runs.

**Comment by rackernexus** [comment]
Build 9 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-b6827be42/). valid for 14 days

**Comment by cyrichardson** [comment]
@edwardjrp Clicking Preview link gives "Page not found". Please let me know if there is anything I can do.

**Comment by edwardjrp** [comment]
build me

**Comment by rackernexus** [comment]
Build 10 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-b6827be42/). valid for 14 days

**Comment by edwardjrp** [comment]
build me

**Comment by rackernexus** [comment]
Build 11 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-b6827be42/docs/ras-databases/). valid for 14 days

**Comment by cyrichardson** [comment]
@edwardjrp Woot!! Preview looks good! This PR can be merged now. Should I do it, or is this something you need to handle for now?

**Pull request merged**
