### PR TITLE
remove all cassandra references

### PR DESCRIPTION
**Pull request by Sterling463**

### CODE REVIEW

**Comment by Sterling463** [comment]
build me

**Comment by Sterling463** [comment]
build me

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 31 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-d10f7f456/docs/ras-databases/). valid for 14 days

**Review by stephamon — APPROVED** [review]

**Pull request merged**
