### PR TITLE
adds test word to spellinglist

### PR DESCRIPTION
**Pull request by Sterling463**

### CODE REVIEW

**Review by WilliamLoy — APPROVED** [review]
lgtm

**Comment by rackernexus** [comment]
Build 25 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-b8c695fe9/docs/ras-databases/). valid for 14 days

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 28 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-382c79d5c/docs/ras-databases/). valid for 14 days

**Pull request merged**
