### PR TITLE
RAS database handbook

### PR DESCRIPTION
**Pull request by chri2547**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-f7af8dfc5c/docs/ras-databases/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-f4ac0e24b9/docs/ras-databases/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-d0c553a491/docs/ras-databases/)

**Review by cyrichardson — APPROVED** [review]
While we are not getting the toc as we'd like, Chris and I decided to merge this PR to get the content up. Then can concentrate on getting the toc to show up. This will make it easier to get help from others. BTW, we are getting the build and preview link.... just not the tocs.

**Pull request merged**
