### PR TITLE
Editorial feedback incorporated

### PR DESCRIPTION
**Pull request by chri2547**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-cde1d0ff6f/docs/ras-databases/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-d5b9b1865a/docs/ras-databases/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-910a1e3575/docs/ras-databases/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-f1fd955009/docs/ras-databases/).

**Comment by cyrichardson** [comment]
Fixes #8

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-5ec12ae22f/docs/ras-databases/)

**Review by cyrichardson — APPROVED** [review]
Made a few changes in your PR. Everything looks good to send to SME, @chri2547. Let me know if you are ready to merge and would like for me to do it.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-e3836a024d/docs/ras-databases/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-f9a8505a3c/docs/ras-databases/). :bow:

**Pull request merged**
