### PR TITLE
Update managed-databases.rst

### PR DESCRIPTION
**Pull request by aaronconklin**
Making text edits on request of Todd Helfter, Director, DBA Services

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 13 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-c93234686/docs/ras-databases/). valid for 14 days

**Comment by cyrichardson** [comment]
@aaronconklin Are there some specific reviewers in your group you'd like to select, or are you just looking for an editorial reveiw.

**Comment by aaronconklin** [comment]
@cyrichardson I do not need any particular reviewer, just permission to merge the request to the live site. The edits look good in staging.

**Review by cyrichardson — APPROVED** [review]

**Comment by cyrichardson** [comment]
@aaronconklin I reviewed your PR changes from a technical editor's perspective and approved it. You can always ask for a review for any PR in the #docs channel and should get 1 reviewer before you merge a PR. The InfoDev team monitors the #docs channel and is always glad to help.

You can merge it now if you are ready. Then ask in the #docs channel to have this PR published to external page. That's a different build than the staging one and currently requires someone with permission to push the external publishing process. 

Thanks a ton for your docs contribution!

**Pull request merged**
